/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Flipkart;

import java.time.Duration;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;

public class App {
    
    // public static ChromeDriver createDriver() {
    //     //TODO Create a new chrome Driver and Return the same
    //       ChromeDriver driver;
    //       WebDriverManager.chromedriver().setup();
    //       driver = new ChromeDriver();
    //       return driver;
    //   }

    public static EdgeDriver createDriver(){
        EdgeDriver driver;
        WebDriverManager.edgedriver().setup();
        driver = new EdgeDriver();
        return driver;
    }  
    public static void printloadtime(EdgeDriver driver){
        long s = System.currentTimeMillis();
        driver.get("https://www.flipkart.com/");
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
        wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//a[@class='_1_3w1N']")));
        long e = System.currentTimeMillis();
        long r = e-s;
        System.out.println("Timetaken for loading the page: "+ r);
        // driver.close();

    }

    public static void main(String[] args) {
    // ChromeDriver driver = createDriver();
    EdgeDriver driver = createDriver();
        try {
            printloadtime(driver);
        } catch (Exception e) {
            // TODO: handle exception
        }
    }
}
